# See docs folder for details on implementation

## Site Settings

### Site Information

title: Recovery Hub Edition Framework
tagline: A base for building Recovery Hub for American Women Writers projects
description: >- # this means to ignore newlines until "baseurl:"
  This site establishes a framework for building Recovery Hub projects using Markdown, Jekyll, and GitHub pages.

### Site Structure

baseurl: "/" # the subpath of your site
url: "https://recoveryhub.github.io/" # should not change for Recovery Hub projects

### Banner image

banner_image: assets/images/recovery-hub-banner.jpg
banner_alt_text: Recovery Hub of American Women Writers with quill icon and pages of a book in the background

### Contact

email: recoveryhub@siue.edu
privacy_notice: https://www.siue.edu/web-privacy-notice/

### Social Accounts

facebook_username: AWWrecoveryhub
twitter_username: AWWRecoveryHub
instagram_username: awwrecoveryhub
github_username:  recoveryhub

### Sponsors / Organization Logos
# Can be overridden in _includes/footer.html instead

sponsors:
  # copy-paste the following 4 lines for each sponsor
  - sponsor:
    name: Southern Illinois University Edwardsville
    link: https://www.siue.edu/
    logo_path: assets/images/siue.png

  - sponsor:
    name: St. Catherine University
    link: https://www.stkate.edu/
    logo_path: assets/images/stkate.png

  - sponsor: 
    name: National Endowment for the Humanities
    link: https://www.neh.gov/
    logo_path: assets/images/neh.webp

  - sponsor:
    name: The IRIS Center at SIUE
    link: https://iris.siue.edu/
    logo_path: assets/images/iris.png
    
  - sponsor: 
    name: University of Nebraska–Lincoln
    link: https://www.unl.edu/
    logo_path: assets/images/unl.png

### Site Setup / Defaults

# Categories listed here must match the 
# categories in defaults, below. 
# The categories are not showing up in the 
# site.categories object  ¯\_(ツ)_/¯

# I am using categories instead of collections because I can then have files with no headmatter, which may make it easier to incorporate files from other projects

category_list: ["no_category", "book", "periodical", "essay", "poem", "documentation"]

# exclude: ["docs"] # once edition is complete, if you want to exclude the documentation from showing you can exclude the docs folder. You can also add any other directories you would like to exclude (i.e. notes, source files, etc.)

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: default
      category: no_category
# Item Types
  - scope:
      path: "item/book"
      type: pages
    values:
      layout: paginate
      category: book
  - scope:
      path: "item/periodical"
      type: pages
    values:
      layout: paginate
      category: periodical
  - scope:
      path: "item/poem"
      type: pages
    values:
      layout: default
      category: poem
# Paratext (Introduction, Essays, Documentation)
  - scope:
      path: "essay"
      type: pages
    values:
      layout: default
      category: essay
  - scope:
      path: "docs"
      type: pages
    values:
      layout: default
      category: documentation
# Pages to add to navigation
# you can alternately add pages to navigation via frontmatter
  - scope:
      path: "about.md"
    values:
      navigation: "true"
  - scope:
      path: "index.md"
    values:
      navigation: "true"
  - scope:
      path: "docs/README.md"
    values:
      navigation: "true"
  - scope:
      path: "docs/listing.html"
    values:
      navigation: "true"

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
